/**:
  ros__parameters:
    zeros:
      footprint_to_neck: 1.2911
      neck_to_eyes: 0.3145
      # neck_to_shoulder: 0.22
      neck_to_shoulder: 0.0
      shoulder_to_wrist: 0.4739
      wrist_to_finger: 0.1583
